---
- hosts: localhost
  tasks: 
  # - name: ZVM Login  
  #   uri: 
  #     url: "https://inpaw0041.amer.corp.xpo.com:9669/v1/session/add"
  #     force_basic_auth: yes
  #     method: POST
  #     user: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
  #     password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
  #     status_code: 200
  #     validate_certs: no
  #     body_format: json 
  #   register: login

  # - name: CheckOutPut
  #   set_stats:
  #     data:
  #       ZertoLogin: '{{login}}'

  - name: VPG Settings Identifier 
    uri: 
      url: "https://inpaw0041.amer.corp.xpo.com:9669/v1/vpgsettings"
      force_basic_auth: yes
      method: POST
      user: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      status_code: 200
      validate_certs: no 
      headers: 
        x-zerto-session: x_zerto_session
        accept: "application/json"
        content-type: "application/json"
      body: "{ }"
      body_format: json
    register: vpgsettings 

  - name: Is vm protected?   
    uri: 
      url: "https://inpaw0041.amer.corp.xpo.com:9669/v1/vms/{{mVMname}}"
      force_basic_auth: yes
      method: POST
      user: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      status_code: 200
      validate_certs: no
      body_format: json 
    register: isProtected